### ISSUE TITLE
{"path": "stdout"} not supported by the CLI

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-cli-client#12]
```
Traceback (most recent call last):
  File "/home/ovos/.venv/bin/ovos-cli-client", line 33, in <module>
    sys.exit(load_entry_point('ovos-cli-client==0.0.1', 'console_scripts', 'ovos-cli-client')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_cli_client/__main__.py", line 63, in main
    for f in os.listdir(log_dir):
             ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'stdout'
```

**Comment by goldyfruit** [comment]
Only way to make it work it to `mkdir ~/stdout` before running the `ovos-cli-client` command.
