### ISSUE TITLE
ovos-cli-client still depends a lot on mycroft

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-cli-client#7]
on a clean raspbian installation of ovos, with the default mycroft.conf ovos-cli-client will fail looking for `/var/log/mycroft` folder. 

This is the message:
```
(ovos-core) denix@sprat:~ $ ovos-cli-client
2023-02-19 09:48:26.887 - OVOS - ovos_config.models:load_local:95 - DEBUG - Configuration /home/denix/ovos-core/lib/python3.9/site-packages/mycroft/configuration/mycroft.conf loaded
2023-02-19 09:48:27.074 - OVOS - ovos_config.models:load_local:99 - DEBUG - Configuration '/etc/mycroft/mycroft.conf' not defined, skipping
2023-02-19 09:48:27.254 - OVOS - ovos_config.models:load_local:99 - DEBUG - Configuration '/home/denix/.config/mycroft/web_cache.json' not defined, skipping
2023-02-19 09:48:27.454 - OVOS - ovos_config.models:load_local:95 - DEBUG - Configuration /home/denix/.config/mycroft/mycroft.conf loaded
2023-02-19 09:48:27.628 - OVOS - ovos_config.models:load_local:99 - DEBUG - Configuration '/etc/xdg/mycroft/mycroft.conf' not defined, skipping
2023-02-19 09:48:27.809 - OVOS - ovos_config.models:load_local:99 - DEBUG - Configuration '/home/denix/.mycroft/mycroft.conf' not defined, skipping
2023-02-19 09:48:27.924 - OVOS - ovos_utils.configuration:<module>:52 - WARNING - configuration moved to the `ovos_config` package. This submodule will be removed in ovos_utils 0.1.0


Traceback (most recent call last):
  File "/home/denix/ovos-core/bin/ovos-cli-client", line 8, in <module>
    sys.exit(main())
  File "/home/denix/ovos-core/lib/python3.9/site-packages/ovos_cli_client/__main__.py", line 55, in main
    for f in os.listdir(log_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/var/log/mycroft'
```

**Comment by JarbasAl** [comment]
you dont seem to be using the latest version, please install from git not pypi, pypi does not yet have the latest

**Comment by denics** [comment]
I confirm git version is working
